version: '3.8'

services:
  ronas_postgres:
    image: postgres
    container_name: ronas_postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - ronas_postgres_data:/var/lib/postgresql/data
#  ronas_test_postgres:
#    image: postgres
#    container_name: ronas_test_postgres
#    ports:
#      - '6501:5432'
#    restart: always
#    environment:
#      - DATABASE_PORT=5432
#      - POSTGRES_PASSWORD=todo_list_pass
#      - POSTGRES_USER=todo_list_user
#      - POSTGRES_DB=todo_list_test_db
#      - POSTGRES_HOST=postgres
#      - POSTGRES_HOSTNAME=test_postgres
#    volumes:
#      - ronas_test_postgres_data:/var/lib/postgresql/data
  ronas_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - ronas_postgres
#      - ronas_test_postgres

volumes:
  ronas_postgres_data:
#  ronas_test_postgres_data: